name: Quality checks
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  quality-checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install poetry
      run: pip install poetry
    - uses: actions/cache@v2
      with:
        path: ~/.cache/pypoetry/virtualenvs
        key: poetry-${{ hashFiles('poetry.lock') }}
    - name: Install dependencies
      run: poetry install --no-root
    - name: Lint, format, sort imports & typecheck
      run: |
        poetry run task quality
    - name: Run tests & generate coverage report
      run: |
        pip install pytest pytest_mock pytest-cov
        pytest --cov=./ --cov-report=xml
    - name: Upload code coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
        name: codecov-umbrella
        fail_ci_if_error: true
