name: Unit tests & Coverage Report
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Run tests & generate coverage report
      run: |
        pip install pytest
        pip install pytest-cov
        pwd
        ls -la
        pytest --cov=./ --cov-report=xml
    - name: Upload code coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
        name: codecov-umbrella
        fail_ci_if_error: true
